apiVersion: apps/v1
kind: Deployment
metadata:
  name: karsajobs-ui-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend 
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: karsajobsui 
        image: yunandar711/karsajobs-ui:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: VUE_APP_BACKEND
          value: "http://192.168.49.2:32161"
